--!strict
-- ReplicatedStorage > Content  (ModuleScript)
-- GENERATED by tools/build_place.py from upload/audio_manifest.json and tools/story.json.
-- Rebuilding the place overwrites this file: change the text in those two files instead
-- (or edit here in Studio if you never plan to rebuild). Times are seconds inside each pack.

export type Line = { id: string, zone: string, start: number, stop: number, text: string }
export type Region = { start: number, stop: number }
export type Track = { start: number, stop: number, loop: boolean }
export type Zone = {
	id: string,
	order: number,
	name: string,
	numeral: string,
	theme: string,
	color: { number },
	music: string,
	video: string,
	insightLine: string?,
	insight: string?,
}
export type Credit = { heading: string, text: string }

local Content = {}

Content.Title = "Nothing Becomes Everything"
Content.Subtitle = "a game by Brandon"
Content.Creator = "Brandon"

-- Brandon's voice lines: one audio file, each line is a region of it.
Content.VoiceFile = "voice_pack.ogg"
Content.VoiceDuration = 159.063
Content.Lines = {
	hub_welcome = { id = "hub_welcome", zone = "hub", start = 0.3, stop = 2.94, text = "Just a friendly reminder that you are amazing." },
	time_1 = { id = "time_1", zone = "time", start = 3.54, stop = 7.42, text = "Time is already eating us. Each second is a small bite." },
	time_2 = { id = "time_2", zone = "time", start = 8.02, stop = 12.58, text = "You are not watching time go by. Time is watching you disappear while it eats you." },
	time_3 = { id = "time_3", zone = "time", start = 13.18, stop = 17.76, text = "Even while you are watching this, it is already taking the next second." },
	hole_1 = { id = "hole_1", zone = "hole", start = 18.36, stop = 24.1, text = "Putting yourself down is like jumping into a hole and asking yourself, why can't I see the sky?" },
	hole_2 = { id = "hole_2", zone = "hole", start = 24.7, stop = 29.66, text = "Every time you say \"I can't do it, I'm not good,\" it's another hand of dirt." },
	hole_3 = { id = "hole_3", zone = "hole", start = 30.26, stop = 35.44, text = "The funny thing is, the ground never pulled you down. Your thoughts kept digging." },
	hole_4 = { id = "hole_4", zone = "hole", start = 36.04, stop = 44.84, text = "The sky never disappeared. The sky never went away. You just stopped looking up. The light never left." },
	hole_step = { id = "hole_step", zone = "hole", start = 45.44, stop = 49.24, text = "One better thought is one step higher." },
	hole_move = { id = "hole_move", zone = "hole", start = 49.84, stop = 53.94, text = "You were never made to look at dirt. You were made to move." },
	glass_1 = { id = "glass_1", zone = "glass", start = 54.54, stop = 62.66, text = "It can also feel like you are in a glass box, and every word goes in like water slowly rising." },
	glass_2 = { id = "glass_2", zone = "glass", start = 63.26, stop = 67.721, text = "But the box is made in your mind, and the water is what you keep holding onto." },
	glass_3 = { id = "glass_3", zone = "glass", start = 68.321, stop = 71.821, text = "What they say is what they say. It is not who you are." },
	glass_4 = { id = "glass_4", zone = "glass", start = 72.421, stop = 77.901, text = "Not everything that tries reaching for you needs to stay in you." },
	road_1 = { id = "road_1", zone = "road", start = 78.501, stop = 87.001, text = "Your feet being tired does not mean the road is over. It means you walked far." },
	road_2 = { id = "road_2", zone = "road", start = 87.601, stop = 95.462, text = "Your mind feels heavy does not mean you are broken. It means that you are carried a lot." },
	road_3 = { id = "road_3", zone = "road", start = 96.062, stop = 104.422, text = "The truth is, you didn't hit a wall. You just met something small and gave it a big name." },
	chains_1 = { id = "chains_1", zone = "chains", start = 105.022, stop = 115.002, text = "If you never walk, you will stay in the same place. If you never run, you will never see how far you could have gone." },
	chains_2 = { id = "chains_2", zone = "chains", start = 115.602, stop = 120.903, text = "Never let your mind lock you in a place your body could have left." },
	chains_3 = { id = "chains_3", zone = "chains", start = 121.503, stop = 128.823, text = "So move right now. Don't stay the same, or \"I can't\" will become your name." },
	chains_4 = { id = "chains_4", zone = "chains", start = 129.423, stop = 134.423, text = "If you stop, it all stops. If you keep going, you keep on growing." },
	everything_1 = { id = "everything_1", zone = "everything", start = 135.023, stop = 142.943, text = "One day you will look back and realize you were walking the whole time. You just didn't see it yet." },
	everything_2 = { id = "everything_2", zone = "everything", start = 143.543, stop = 150.023, text = "Keep on going, even when it feels like nothing, because one day that nothing becomes everything." },
	everything_3 = { id = "everything_3", zone = "everything", start = 150.623, stop = 158.463, text = "You don't have to be great today. You don't have to be the best. You just have to not stop." },
} :: { [string]: Line }

Content.SfxFile = "sfx_pack.ogg"
Content.SfxDuration = 40.19
Content.Sfx = {
	collect = { start = 0.3, stop = 1.9 },
	step_rise = { start = 2.25, stop = 3.25 },
	glass_shatter = { start = 3.6, stop = 5.8 },
	water_drain = { start = 6.15, stop = 7.95 },
	chains_break = { start = 8.3, stop = 12.85 },
	wall_shrink = { start = 13.2, stop = 19 },
	zone_complete = { start = 19.35, stop = 23.85 },
	clock_tick = { start = 24.2, stop = 25.1 },
	heartbeat = { start = 25.45, stop = 26.02 },
	whoosh = { start = 26.37, stop = 27.12 },
	portal = { start = 27.47, stop = 29.67 },
	ui_click = { start = 30.02, stop = 30.14 },
	finale_boom = { start = 30.49, stop = 34.99 },
	bell = { start = 35.34, stop = 39.84 },
} :: { [string]: Region }

Content.MusicFile = "music_pack.ogg"
Content.MusicDuration = 291.929
Content.Music = {
	hub = { start = 0.5, stop = 64.5, loop = true },
	time = { start = 65.5, stop = 86.071, loop = true },
	hole = { start = 87.071, stop = 121.357, loop = true },
	glass = { start = 122.357, stop = 146.357, loop = true },
	road = { start = 147.357, stop = 171.357, loop = true },
	chains = { start = 172.357, stop = 216.928, loop = true },
	everything = { start = 217.928, stop = 245.357, loop = true },
	finale = { start = 246.357, stop = 290.929, loop = false },
} :: { [string]: Track }

-- Optional video files (upload/videos). Their asset ids go in Config.Videos.
Content.VideoFiles = {
	hub = "videos/video_hub.mp4",
	time = "videos/video_time.mp4",
	hole = "videos/video_hole.mp4",
	glass = "videos/video_glass.mp4",
	road = "videos/video_road.mp4",
	chains = "videos/video_chains.mp4",
	everything = "videos/video_everything.mp4",
} :: { [string]: string }

-- The journey, in order. Each zone ends with its Insight (the key line).
Content.Zones = {
	{
		id = "hub",
		order = 0,
		name = "The Clearing",
		numeral = "",
		theme = "Where every journey starts.",
		color = { 120, 225, 240 },
		music = "hub",
		video = "hub",
		insightLine = nil,
		insight = nil,
	},
	{
		id = "time",
		order = 1,
		name = "The Clock Tower",
		numeral = "I",
		theme = "Each second is a small bite.",
		color = { 255, 196, 110 },
		music = "time",
		video = "time",
		insightLine = "time_3",
		insight = "Even while you are watching this, it is already taking the next second.",
	},
	{
		id = "hole",
		order = 2,
		name = "The Hole",
		numeral = "II",
		theme = "Why can't I see the sky?",
		color = { 160, 176, 255 },
		music = "hole",
		video = "hole",
		insightLine = "hole_step",
		insight = "One better thought is one step higher.",
	},
	{
		id = "glass",
		order = 3,
		name = "The Glass Box",
		numeral = "III",
		theme = "Every word goes in like water slowly rising.",
		color = { 110, 214, 255 },
		music = "glass",
		video = "glass",
		insightLine = "glass_4",
		insight = "Not everything that tries reaching for you needs to stay in you.",
	},
	{
		id = "road",
		order = 4,
		name = "The Road",
		numeral = "IV",
		theme = "Your feet being tired does not mean the road is over.",
		color = { 255, 156, 112 },
		music = "road",
		video = "road",
		insightLine = "road_3",
		insight = "The truth is, you didn't hit a wall. You just met something small and gave it a big name.",
	},
	{
		id = "chains",
		order = 5,
		name = "Chains",
		numeral = "V",
		theme = "If you never run, you will never see how far you could have gone.",
		color = { 196, 146, 255 },
		music = "chains",
		video = "chains",
		insightLine = "chains_2",
		insight = "Never let your mind lock you in a place your body could have left.",
	},
	{
		id = "everything",
		order = 6,
		name = "The Summit",
		numeral = "VI",
		theme = "You were walking the whole time.",
		color = { 255, 214, 140 },
		music = "everything",
		video = "everything",
		insightLine = "everything_2",
		insight = "Keep on going, even when it feels like nothing, because one day that nothing becomes everything.",
	},
} :: { Zone }

Content.Story = {
	holeCarvings = { "I CAN'T", "I'M NOT GOOD", "WHY TRY", "I CAN'T DO IT" },
	betterThoughts = { "I CAN", "I'M LEARNING", "ONE STEP", "I'M STRONG", "KEEP GOING", "LOOK UP", "I'M ENOUGH" },
	glassWords = { "WORTHLESS", "WEIRD", "TOO QUIET", "NOT GOOD", "I CAN'T" },
	monument = { "NOTHING", "BECOMES", "EVERYTHING" },
	loadingMessages = { "Lighting the campfire...", "Winding the clock...", "Looking up...", "Keep going..." },
	bellLabel = "I CAN",
	credits = {
		{ heading = "", text = "NOTHING BECOMES EVERYTHING" },
		{ heading = "", text = "a game by Brandon" },
		{ heading = "Words and voice", text = "Brandon" },
		{ heading = "Music and sound", text = "made for this game" },
		{ heading = "", text = "Thank you for playing." },
		{ heading = "", text = "Keep going." },
	} :: { Credit },
}

return Content
