"""Write CUESHEET.md: every line with its timecode, voice effect, shot and
sound cue, so the edit can be checked (or rebuilt by hand) inside CapCut."""
import json
from pathlib import Path

import build_video
import edl

ROOT = Path(__file__).resolve().parent

FX_TEXT = {
    "warm": "clean + small room",
    "hall": "hall reverb",
    "big": "hall + cathedral reverb",
    "intimate": "close and dry, extra warmth",
    "echo": "hall + echo on the last word",
    "title": "reverse-reverb rise in, cathedral, echo out",
    "reveal": "cathedral + echo + long space tail",
    "memory": "filtered 'voice in your head' + chorus + hall",
    "dark": "pitched-down shadow voice + dark cathedral",
    "chorus": "doubled into several voices ('we') + hall",
    "center": "reverse rise in, close voice, long space tail",
    "final": "close and dry, echo + space tail after the last word",
}

TRANSITION = {
    "fade": "dissolve", "fadeblack": "dip to black", "fadewhite": "white flash",
    "hblur": "blur dissolve", "zoomin": "zoom-in", None: "-",
}


def tc(t):
    m, s = divmod(t, 60)
    return f"{int(m):02d}:{s:05.2f}"


def main():
    tl = json.load(open(ROOT / "out/timeline.json"))
    shots = build_video.resolve_shots(tl)
    lines = tl["lines"]
    cues_by_line = {}
    for c in tl["cues"]:
        cues_by_line.setdefault(c["line"], []).append(f"{c['kind']} @ {tc(c['t'])}")

    rows = []
    for ln in lines:
        mine = [s for s in shots if ln["start"] - 0.6 <= s["cut"] < (
            lines[ln["i"] + 1]["start"] - 0.6 if ln["i"] + 1 < len(lines) else 1e9)]
        shot_txt = "<br>".join(
            f"{s['clip']} from {s['src_in']:.1f}s ({TRANSITION.get(s['tr'], s['tr'])}"
            f"{', slow-mo x' + format(1 / s['speed'], '.1f') if s['speed'] != 1 else ''})" for s in mine) or "(continues)"
        rows.append(f"| {tc(ln['start'])} | {ln['text']} | {FX_TEXT[ln['fx']]} | {shot_txt} | "
                     f"{'<br>'.join(cues_by_line.get(ln['i'], [])) or ''} |")

    md = [
        "# Cue sheet: 0922 narration-match (Endless Destiny announcement)",
        "",
        f"Total length **{tc(tl['duration'])}** at 24 fps. Generated by `make_cuesheet.py` from `edl.py`,",
        "so if you change the edit, rebuild and regenerate this file.",
        "",
        "Timecodes are where each line's first word lands in the finished video.",
        "",
        "| Time | Line | Voice effect | Picture (clip, in-point, transition) | Sound design |",
        "|---|---|---|---|---|",
        *rows,
        "",
        "## Clips",
        "",
        "| Clip | Higgsfield generation |",
        "|---|---|",
        *[f"| {k} | `{v}` |" for k, v in edl.CLIPS.items()],
        "",
    ]
    (ROOT / "CUESHEET.md").write_text("\n".join(md))
    print("wrote CUESHEET.md")


if __name__ == "__main__":
    main()
